title: MICCAI 2024 - Tutorial on Implicit Neural Representations
email: julian.mcginnis@tum.de
description: Tutorial in Conjunction with MICCAI 2024
  ---
baseurl: "/" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
include: ['_pages']

# Google Analytics
google_analytics: UA-158554905-1

